spring:
  datasource:
    url: jdbc:mysql://192.168.56.3:3306/hotel-server?useUnicode=true&characterEncoding=UTF-8
    username: johnson
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

# JWT配置
jwt:
  # 密匙KEY
  secret: JWTSecret
  # HeaderKEY
  tokenHeader: X-TOKEN
  # Token前缀字符
  tokenPrefix: hotel-
  # 过期时间 单位秒 1天后过期=86400 7天后过期=604800
  expiration: 86400

# 自定义上传配置项
file:
  local:
    # 实际保存路径
    path: D:/java/hotel-file
    # 服务器访问路径
    server-path: /file